# Generated by Django 3.0 on 2020-10-14 08:02

from django.db import migrations, models
import django_cropper_image.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_cropper_image.fields.ImageCropperField(upload_to='image')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
